// ==================== ITINERARIO VIAGGIO MARTINA ====================
// 18 Luglio - 6 Agosto 2026: Thailandia 🇹🇭 • Giappone 🇯🇵 • Corea 🇰🇷

const itineraryData = [
{day:1,date:"Sabato 18/07/2026",title:"Volo Milano → Bangkok",route:"MXP ➔ DEL ➔ BKK",km:0,time:"Volo notturno ~13h + scalo",sunrise:"—",sunset:"—",fuso:"Italia → India (+3,5h) → Thailandia (+5h)",hotel:"A bordo del volo",desc:"Partenza da Milano Malpensa alle 21:15. Volo notturno con scalo a Delhi. Arrivo a Bangkok nella giornata del 19 luglio, ora locale. Volo lungo: portare mascherina, cuscino, calze comode. Documenti: passaporto con validità residua >6 mesi, eventuale visto Thailandia (esenzione 60 giorni per italiani).",logistics:"Check-in online 24h prima. Bagaglio a mano: 7-10 kg. Liquidi max 100ml in busta trasparente.",transferInfo:"<p><strong>Aeroporto Milano Malpensa (MXP):</strong> presentarsi al Terminal 1 almeno 3 ore prima per voli intercontinentali.</p><p>Per raggiungere MXP da Milano centro: treno Malpensa Express da Cadorna (€13, 40 min) oppure autobus.</p><p>All'arrivo a Delhi, seguiranno le indicazioni per il transfer e l'imbarco sul volo Bangkok.</p>",food:["Pasti a bordo del volo (pre-ordine opzionale)","Acqua e snack leggeri nel bagaglio a mano"],supermarkets:["Nessuno (in volo)"],region:"Italia → Asia",gmaps:"https://maps.google.com/?q=Milano+Malpensa+Airport",phaseId:"phase1"},

{day:2,date:"Domenica 19/07/2026",title:"Arrivo a Bangkok",route:"Aeroporto BKK ➔ Hotel Bangkok",km:30,time:"45-90 min (Airport Rail Link + taxi)",sunrise:"06:00",sunset:"18:50",fuso:"Indochina Time (GMT+7)",hotel:"Mandarin Hotel Managed by Centre Point (€244,22)",desc:"Arrivo a Bangkok Suvarnabhumi (BKK). Trasferimento in hotel con Airport Rail Link fino a Phaya Thai, poi breve taxi. Check-in e riposo per recuperare il jet lag. Primo approccio alla città: esplorazione serale della zona Chinatown o Khao San Road per cena e atmosfera.",logistics:"Airport Rail Link: 45 min fino a Phaya Thai Station (THB 45). Taxi meter: usare sempre il tassametro o Grab/Bolt.",food:["Jay Fai (Street food leggendario, prenotare!)","Err Urban Rustic Thai (Cucina tailandese moderna)","Canton House (Cucina cinese-thai)","Or Tor Kor Market (Street food autentico)"],supermarkets:["7-Eleven (diffusissimi ovunque)","Big C Supercenter Pratunam","Tops Market CentralWorld"],region:"Bangkok 🇹🇭",gmaps:"https://maps.google.com/?q=Mandarin+Hotel+Managed+by+Centre+Point+Bangkok",phaseId:"phase1"},

{day:3,date:"Lunedì 20/07/2026",title:"Bangkok: Templi Reali",route:"Hotel ➔ Grande Palazzo ➔ Wat Pho ➔ Wat Arun",km:15,time:"Mezza giornata",sunrise:"06:00",sunset:"18:50",fuso:"Indochina Time (GMT+7)",hotel:"Mandarin Hotel Managed by Centre Point",desc:"Mattina dedicata al Grande Palazzo Reale e Wat Phra Kaew (Tempio del Buddha di Smeraldo), vestiti con spalle e ginocchia coperte. A piedi al Wat Pho (Buddha sdraiato, 46m). Pomeriggio: traghetto sul fiume Chao Phraya fino a Wat Arun (Tempio dell'Alba). Sera: massaggio tailandese tradizionale.",logistics:"Dress code rigoroso: no pantaloni corti, no canotte, no sandali aperti. Si noleggiano sarong all'ingresso (200 THB a deposito).",food:["Thip Samai (Pad Thai leggendario)","Err Urban Rustic Thai","Raan Jay Fai (se non già visitata)"],supermarkets:["7-Eleven","Big C Supercenter"],region:"Bangkok 🇹🇭",gmaps:"https://maps.google.com/?q=Grand+Palace+Bangkok",phaseId:"phase1"},

{day:4,date:"Martedì 21/07/2026",title:"Bangkok: Mercati & Quartieri",route:"Chatuchak ➔ Chinatown ➔ Khao San Road",km:25,time:"Intera giornata",sunrise:"06:00",sunset:"18:50",fuso:"Indochina Time (GMT+7)",hotel:"Mandarin Hotel Managed by Centre Point",desc:"Mattina al mercato di Chatuchak (sabato/domenica: oggi alternativo MBK Center). Esplorazione Chinatown (Yaowarat): templi, street food, vicoli. Sera a Khao San Road per l'atmosfera backpacker. Tramvia e BTS Skytrain per muoversi.",logistics:"MBK Center: aperto tutti i giorni. BTS Skytrain fermata National Stadium.",food:["T&K Seafood (Chinatown, vista strada)","Guay Jub Mr. Joe (Zuppa di noodles)","Jay Mai's (Street food)"],supermarkets:["MBK Food Court (economico e vario)","Tops Market Siam Paragon"],region:"Bangkok 🇹🇭",gmaps:"https://maps.google.com/?q=Chatuchak+Market+Bangkok",phaseId:"phase1"},

{day:5,date:"Mercoledì 22/07/2026",title:"Bangkok: Mercato Galleggiante & Massaggio",route:"Damnoen Saduak ➔ Bangkok",km:100,time:"Intera giornata (gita)",sunrise:"06:00",sunset:"18:50",fuso:"Indochina Time (GMT+7)",hotel:"Mandarin Hotel Managed by Centre Point",desc:"Partenza presto (06:30) per il mercato galleggiante di Damnoen Saduak (1,5h da Bangkok). Barca tra i canali, bancarelle su barche. Pranzo sul posto. Rientro Bangkok e pomeriggio libero: massaggio tailandese al Wat Pho Massage School o shopping mall (Siam Paragon, ICONSIAM).",logistics:"Tour organizzato o auto privata. Partire presto per evitare caldo e folla.",food:["Cibo sui battelli al mercato galleggiante","Ristorante panoramico ICONSIAM","Massaggio tailandese al Wat Pho"],supermarkets:["ICONSIAM (mall con supermercato)"],region:"Bangkok 🇹🇭",gmaps:"https://maps.google.com/?q=Damnoen+Saduak+Floating+Market",phaseId:"phase1"},

{day:6,date:"Giovedì 23/07/2026",title:"Bangkok ➔ Volo ➔ Okinawa",route:"BKK ➔ OKA (8:25-15:05)",km:0,time:"Volo 4h40 + fuso +2h",sunrise:"05:55",sunset:"19:25",fuso:"Japan Time (GMT+9)",hotel:"Hotel Cocktail Stay Naha (€265,67)",desc:"Mattina relax e ultima colazione a Bangkok. Trasferimento a Suvarnabhumi per il volo mattutino verso Okinawa. All'arrivo a Naha (15:05), trasferimento in hotel nella zona di Kokusai Dori. Sera: esplorazione della via principale illuminata e cena con cucina Okinawana (soba, taco rice, goya champuru).",logistics:"Volo: portare passaporto. Transfer Naha: monorail Yui Rail fino a Makishi o Asato (15 min, ¥260).",food:["Ichibanya Sushi (Catena sushi locale)","Taco Rice King (Piatto tipico okinawano)","Makishi Market (Street food al coperto)"],supermarkets:["MaxValu Express (convenient store locale)","San-A Naha Main Place"],region:"Bangkok ➔ Okinawa",gmaps:"https://maps.google.com/?q=Hotel+Cocktail+Stay+Naha+Okinawa",phaseId:"phase2"},

{day:7,date:"Venerdì 24/07/2026",title:"Okinawa: Naha & Castello Shuri",route:"Hotel ➔ Castello Shuri ➔ Kokusai Dori",km:10,time:"Mezza giornata",sunrise:"05:55",sunset:"19:25",fuso:"Japan Time (GMT+9)",hotel:"Hotel Cocktail Stay Naha",desc:"Visita al Castello Shuri (ricostruito dopo incendio 2019, patrimonio UNESCO). Passeggiata nel parco del castello. Pranzo tipico a Sobe. Pomeriggio: Kokusai Dori (la strada internazionale) e Makishi Market. Sera: spiaggia di Naminoue e tramonto.",logistics:"Monorail fino a Shuri Station. Costo parcheggio a Shuri: ¥300/h.",food:["Sobe Soba (Cucina tradizionale della corte Ryukyu)","Yukura (Cena tradizionale Ryukyu)","Tacos & Tacos Okinawa"],supermarkets:["Makishi Public Market (Souvenir e street food)"],region:"Okinawa 🇯🇵",gmaps:"https://maps.google.com/?q=Shuri+Castle+Naha",phaseId:"phase2"},

{day:8,date:"Sabato 25/07/2026",title:"Okinawa: Spiagge & Mare",route:"Naha ➔ Spiagge ➔ Churaumi Aquarium",km:120,time:"Intera giornata",sunrise:"05:55",sunset:"19:25",fuso:"Japan Time (GMT+9)",hotel:"Hotel Cocktail Stay Naha",desc:"Noleggio auto o autobus per la giornata. Spiagge paradisiache: Emerald Beach, Manza Beach. Pranzo a base di pesce fresco. Pomeriggio: Churaumi Aquarium (uno dei più grandi al mondo, con squali balena e mante). Rientro a Naha in serata.",logistics:"Autobus Yanbaru Express o auto a noleggio (~¥5000/giorno). Aquarium chiude alle 18:00 (ultimo ingresso 17:00).",food:["Onna Soba (Pasta Okinawana tipica)","Marruya (Specialità Awamori)","Cafe Bikkuriya"],supermarkets:["Aeon Mall Okinawa Rycom (lungo la strada)"],region:"Okinawa 🇯🇵",gmaps:"https://maps.google.com/?q=Churaumi+Aquarium+Okinawa",phaseId:"phase2"},

{day:9,date:"Domenica 26/07/2026",title:"Okinawa: Relax & Cultura",route:"Naha ➔ Bise Fukugi Tree Road ➔ Hotel",km:30,time:"Mezza giornata",sunrise:"05:55",sunset:"19:25",fuso:"Japan Time (GMT+9)",hotel:"Hotel Cocktail Stay Naha",desc:"Ultima mattina a Okinawa. Visita al villaggio tradizionale Bise con la sua strada alberata da Fukugi. Pranzo di pesce. Pomeriggio libero: ultimo tuffo in spiaggia o shopping a Kokusai Dori. Sera: preparativi per il trasferimento in Giappone continentale.",logistics:"Yui Rail + autobus locale per Bise. Costo vita: più caro della media giapponese.",food:["Yachimun no Mise (Cucina con stoviglie in ceramica locale)","Ukishiro Garden Restaurant","Helios (Hawaiian Okinawan fusion)"],supermarkets:["Don Quijote Naha (Discount store)","Ryubo Department Store"],region:"Okinawa 🇯🇵",gmaps:"https://maps.google.com/?q=Bise+Fukugi+Tree+Road",phaseId:"phase2"},

{day:10,date:"Lunedì 27/07/2026",title:"Okinawa ➔ Takamatsu",route:"OKA ➔ TAK (14:05-16:05)",km:0,time:"Volo 2h + fuso -1h",sunrise:"05:15",sunset:"19:10",fuso:"Japan Time (GMT+9)",hotel:"Hotel AreaOne Takamatsu City (€39,38)",desc:"Volo breve Okinawa-Takamatsu (Shikoku). Arrivo pomeriggio. Check-in hotel e passeggiata nel centro di Takamatsu, città portuale con atmosfera rilassata. Sera: cena tipica con udon di Sanuki (famosi in tutto il Giappone).",logistics:"Aeroporto Takamatsu: collegato al centro con autobus Kotoden (40 min, ¥760).",food:["Yamada Udon (Sanuki udon artigianale)","Nakano Udon School (Fai la tua udon!)","Tsudoi (Set menu con udon)"],supermarkets:["Marugame Seimenjo (Pasta udon confezionata)","MaxValu Takamatsu"],region:"Okinawa ➔ Shikoku",gmaps:"https://maps.google.com/?q=Hotel+AreaOne+Takamatsu+City",phaseId:"phase3"},

{day:11,date:"Martedì 28/07/2026",title:"Takamatsu ➔ Naoshima",route:"Takamatsu ➔ Naoshima (traghetto) ➔ Hotel",km:30,time:"Traghetto 30-50 min",sunrise:"05:15",sunset:"19:10",fuso:"Japan Time (GMT+9)",hotel:"Vacation House YOKOMBO Naoshima (€189,86)",desc:"Traghetto Takamatsu-Naoshima (Tonosho port). Isola dell'arte contemporanea: Chichu Art Museum (progetti di Monet), Benesse House, Art House Project, e la celebre zucca gialla di Yayoi Kusama. Pernottamento in vacation house sull'isola per esperienza completa.",logistics:"Traghetti: Shikoku Kaihatsu o Benesse Line. Biglietti acquistabili online o al porto. Sull'isola: biciclette a noleggio (¥500/giorno) o autobus locale.",food:["Cafe Konichiwa (Sull'isola)","Shioya Diner","Museum Restaurant Benesse"],supermarkets:["Spaccio sull'isola molto limitato (portare provviste da Takamatsu)"],region:"Naoshima 🇯🇵",gmaps:"https://maps.google.com/?q=Vacation+House+YOKOMBO+Naoshima",phaseId:"phase3"},

{day:12,date:"Mercoledì 29/07/2026",title:"Naoshima ➔ Kobe",route:"Naoshima ➔ Kobe (traghetto + treno)",km:200,time:"4-5h totali",sunrise:"05:15",sunset:"19:00",fuso:"Japan Time (GMT+9)",hotel:"Kobe Meriken Park Oriental Hotel (€192,95)",desc:"Mattina sull'isola, completamento visita musei. Traghetto + treno per Kobe. Arrivo pomeriggio. Sistemazione al Meriken Park Oriental Hotel, vista porto. Sera: passeggiata sul lungomare, Kobe Port Tower illuminato, cena in zona Chinatown Nankinmachi.",logistics:"Traghetto Naoshima-Kojima (o Himeji), poi treno JR per Kobe (~1,5h).",food:["Kobe Beef Kikuchi (Manzo di Kobe vero!)","Nankinmachi Chinatown (Street food cinese-giapponese)","Ristorante yakiniku di Kobe"],supermarkets:["Daiei Motomachi (Supermercato gourmet)"],region:"Kobe 🇯🇵",gmaps:"https://maps.google.com/?q=Kobe+Meriken+Park+Oriental+Hotel",phaseId:"phase3"},

{day:13,date:"Giovedì 30/07/2026",title:"Kobe: Manzo, Sake & Vista",route:"Kobe Beef ➔ Sake Brewery ➔ Nunobiki",km:15,time:"Intera giornata",sunrise:"05:15",sunset:"19:00",fuso:"Japan Time (GMT+9)",hotel:"Kobe Meriken Park Oriental Hotel",desc:"Mattina: pranzo Kobe Beef (prenotare!). Visita al Sake Brewery Nada district (le più antiche fabbriche). Pomeriggio: funivia Nunobiki Herb Garden, vista panoramica su Kobe e il porto. Sera: cena nell'elegante zona Sannomiya.",logistics:"Sake Breweries: Hakutsuru Sake Brewery Museum, gratuito. Funivia: base a Shin-Kobe Station.",food:["Mouriya Honten (Kobe beef teppanyaki storico)","Hakutsuru Sake Brewery","Caffè Sannomiya (Cucina fusion)"],supermarkets:["Kobe Hankyu Department Store"],region:"Kobe 🇯🇵",gmaps:"https://maps.google.com/?q=Nunobiki+Herb+Garden+Kobe",phaseId:"phase3"},

{day:14,date:"Venerdì 31/07/2026",title:"Kobe ➔ Osaka",route:"Kobe ➔ Osaka (30 min treno)",km:40,time:"30 min JR",sunrise:"05:15",sunset:"18:55",fuso:"Japan Time (GMT+9)",hotel:"KOKO HOTEL Osaka Namba Sennichimae (€83,37)",desc:"Trasferimento breve a Osaka. Check-in hotel in zona Namba (cuore pulsante della città). Pomeriggio: esplorazione di Dotonbori, Glico Sign, street food (takoyaki, okonomiyaki, kushikatsu). Sera: vita notturna neon di Namba.",logistics:"JR Kobe Line: 30 min fino a Osaka Station, poi metro fino a Namba. Treni frequenti ogni 5-10 min.",food:["Kanidoraku (Takoyaki eccellente)","Mizuno (Okonomiyaki storico)","Daruma (Kushikatsu)"],supermarkets:["Don Quijote Dotonbori (24h)","Gourmet City Namba"],region:"Osaka 🇯🇵",gmaps:"https://maps.google.com/?q=KOKO+HOTEL+Osaka+Namba+Sennichimae",phaseId:"phase4"},

{day:15,date:"Sabato 01/08/2026",title:"Osaka: Castello & teamLab",route:"Osaka Castle ➔ teamLab ➔ Shinsekai",km:15,time:"Intera giornata",sunrise:"05:15",sunset:"18:55",fuso:"Japan Time (GMT+9)",hotel:"Hotel Nikko Kansai Airport (€116,90)",desc:"Mattina: Castello di Osaka (esterno e parco), simbolo della città. Trasferimento al teamLab Botanical Garden (esperienza immersiva digitale). Sera: zona Shinsekai, kushikatsu e atmosfera retro. Ultima notte giapponese: cena di pesce al Kuromon Market (se orario). Ultima notte in aeroporto per volo mattutino.",logistics:"teamLab: prenotazione obbligatoria online. Hotel Nikko Kansai: 5 min a piedi dal terminal.",food:["Tsutenkaku Tower (Vista panoramica + kushikatsu)","Kuromon Ichiba Market (Pesce fresco)","Kame Sushi (Sushi eccellente)"],supermarkets:["Kuromon Market (Pesce, dolci, souvenir)"],region:"Osaka → Kansai Airport",gmaps:"https://maps.google.com/?q=Hotel+Nikko+Kansai+Airport",phaseId:"phase4"},

{day:16,date:"Domenica 02/08/2026",title:"Osaka ➔ Seul",route:"KIX ➔ ICN (7:40-9:35)",km:0,time:"Volo 2h55",sunrise:"05:30",sunset:"19:25",fuso:"Korea Time (GMT+9, stesso fuso)",hotel:"HOMES Stay Myeongdong (€352,32)",desc:"Volo mattutino Osaka-Seul. Arrivo a Incheon (ICN). Trasferimento a Myeongdong (cuore dello shopping e street food coreano). Check-in in hotel. Primo pomeriggio: esplorazione di Myeongdong Cathedral, N Seoul Tower (Namsan). Sera: street food e barbecue coreano.",logistics:"Da Incheon a Myeongdong: AREX Express (43 min, ₩9,500) o All Stop (60 min, ₩4,150). Taxi: ~₩65,000.",food:["Myeongdong Kyoja (Kalguksu, gnocchi)","Yeongyang Center (Samgyetang, zuppa di pollo)","Bbq Chicken & Beer (Chimaek)"],supermarkets:["Lotte Department Store Myeongdong (Food court)","GS25 / CU / 7-Eleven (Diffusi ovunque)"],region:"Osaka ➔ Seul",gmaps:"https://maps.google.com/?q=HOMES+Stay+Myeongdong+Seoul",phaseId:"phase5"},

{day:17,date:"Lunedì 03/08/2026",title:"Seul: Palazzi & Quartieri Storici",route:"Gyeongbokgung ➔ Bukchon ➔ Insadong",km:10,time:"Intera giornata",sunrise:"05:30",sunset:"19:25",fuso:"Korea Time (GMT+9)",hotel:"HOMES Stay Myeongdong",desc:"Mattina: Gyeongbokgung, palazzo principale della dinastia Joseon con guardia in costume (cambio ore 10:00/14:00). Vestiti hanbok noleggiati per accesso gratuito al palazzo. Vicino: villaggio tradizionale Bukchon Hanok. Pomeriggio: Insadong (gallerie, tè, street food). Sera: zona Gwangjang Market (street food + shopping).",logistics:"Vestiti hanbok: 1,5-2h tour del palazzo. Cambio guardia: ore 10:00 e 14:00 (tranne martedì).",food:["Tosokchon Samgyetang (Zuppa di ginseng, famoso)","Gwangjang Market (Bindaetteok, mayak gimbap)","Ssamji-gil (Insadong)"],supermarkets:["E-Mart (Catena coreana, ottima per snack)","Olive Young (Cosmetici coreani)"],region:"Seul 🇰🇷",gmaps:"https://maps.google.com/?q=Gyeongbokgung+Palace+Seoul",phaseId:"phase5"},

{day:18,date:"Martedì 04/08/2026",title:"Seul: Hongdae & Gangnam",route:"Hongdae ➔ Han River Park ➔ Gangnam",km:20,time:"Intera giornata",sunrise:"05:30",sunset:"19:25",fuso:"Korea Time (GMT+9)",hotel:"HOMES Stay Myeongdong",desc:"Mattina: Hongdae (universitario, street art, caffè, performance dal vivo). Pranzo: K-food tipico. Pomeriggio: passeggiata al parco del fiume Han (Hangang Park), opzionale pedalò. Sera: Gangnam (COEX Mall, tempio Bongeunsa illuminato), BBQ coreano congedandosi dalla città.",logistics:"Metro: linea 2 fino a Hongdae-ipgu e Gangnam. Seoul Pass per trasporti illimitati.",food:["Yoogane (Dakgalbi, pollo piccante)","Maple Tree House (BBQ di qualità)","Oasis (Bibimbap)"],supermarkets:["COEX Mall (Shopping + food)","E-Mart Hongdae"],region:"Seul 🇰🇷",gmaps:"https://maps.google.com/?q=Hongdae+Seoul",phaseId:"phase5"},

{day:19,date:"Mercoledì 05/08/2026",title:"Seul: N Seoul Tower & Shopping",route:"N Seoul Tower ➔ Myeongdong Shopping",km:10,time:"Mezza giornata",sunrise:"05:30",sunset:"19:25",fuso:"Korea Time (GMT+9)",hotel:"HOMES Stay Myeongdong",desc:"Ultimo giorno a Seul. Mattina: N Seoul Tower (Namsan Tower) con vista panoramica, funivia. Pomeriggio: shopping di souvenir a Myeongdong (cosmetici K-beauty, maschere, street food). Sera: ultimo barbecue coreano o cena a base di bibimbap. Preparativi per il rientro in Italia.",logistics:"N Seoul Tower: cabinovia da Namsan Cable Car Station, 5 min. Banchetto finale coreano, prenotare in anticipo.",food:["Myeongdong Night Market (Street food serale)","Noryangjin Fish Market (Pesce freschissimo)","Tosokchon Samgyetang"],supermarkets:["Lotte World Tower (Mall + supermercato)","Olive Young (Acquisto cosmetici)"],region:"Seul 🇰🇷",gmaps:"https://maps.google.com/?q=N+Seoul+Tower",phaseId:"phase5"},

{day:20,date:"Giovedì 06/08/2026",title:"Seul ➔ Volo ➔ Milano",route:"ICN ➔ MXP (13:45-20:00)",km:0,time:"Volo 12h15 (con scalo probabile)",sunrise:"05:30",sunset:"19:20",fuso:"Korea Time → Italia (GMT+9 → GMT+2)",hotel:"A bordo del volo",desc:"Ultima mattina a Seul. Trasferimento a Incheon per il volo pomeriggio. Arrivo a Milano alle 20:00. Fine del viaggio!",logistics:"Presentarsi a Incheon almeno 3h prima per voli intercontinentali. AREX da Seoul Station: 60 min.",food:["Ultima colazione coreana in hotel","Pasti a bordo del volo","Acqua e snack per il viaggio"],supermarkets:["Incheon Airport Duty Free (Ultimi acquisti)"],region:"Seul ➔ Milano",gmaps:"https://maps.google.com/?q=Incheon+International+Airport",phaseId:"phase5"}
];
